### ISSUE TITLE
ESTAB timeperiod = 999

### ISSUE THREAD

**Issue by BrendenBe1** [DrylandEcology/rSOILWAT2#114]
when running devtools::run_examples() the runs fail because estab timeperiod is set to 999 (see below). The values are set correctly in the outsetup.in file and when loading the RDS files the values are correct also but when running an example the estab value gets set to 999, causing the run to fail 

> x <- new("swInputData")
>       [,1] [,2]
>  [1,]    0    0
>  [2,]    0    3
>  [3,]    0    3
>  [4,]    0    3
>  [5,]    0    3
>  [6,]    0    0
>  [7,]    0    3
>  [8,]    0    3
>  [9,]    0    3
> [10,]    0    3
> [11,]    0    3
> [12,]    0    3
> [13,]    0    3
> [14,]    0    3
> [15,]    0    3
> [16,]    0    3
> [17,]    0    3
> [18,]    0    3
> [19,]    0    3
> [20,]    0    3
> [21,]    0    0
> [22,]    0    3
> [23,]    0    3
> [24,]    0    3
> [25,]    0    3
> [26,]    0    3
> [27,]    0    3
> [28,]    0    0
> [29,]    3  999
> [30,]    0    3

> Error in validObject(.Object) : 
>   invalid class “swOUT” object: @timeSteps values must in SW_OUTNPERIODS

**Comment by dschlaep** [comment]
@BrendenBe1 I cannot reproduce this error. `devtools::run_examples()` runs without error both for the `master` branch and the development branch `rSOILWAT_new_soilwat_output`.

**Comment by BrendenBe1** [comment]
I still get the error. I noticed when I switch from rSOILWAT2 master to rSOILWAT_new_soilwat_output it doesn't update which branch src/SOILWAT2 is pointing too. After switching to the soilwat_save_output branch and updating the input test objects I still get the error.

**Comment by dschlaep** [comment]
Are you accounting for the bug #95? And properly clean the library file and shared object after switching and/or updating c code?

**Comment by BrendenBe1** [comment]
yes, I have been cleaning SOILWAT2 before installing rSOILWAT.

**Comment by dschlaep** [comment]
As in removing `src/SOILWAT2/libSOILWAT2.a` and `src/rSOILWAT2.so`?

My output:
```
git status
> On branch rSOILWAT_new_soilwat_output
> Your branch is up to date with 'origin/rSOILWAT_new_soilwat_output'.
> 
> nothing to commit, working tree clean
```

```
R
> ...
devtools::clean_dll()
devtools::load_all()
>  ...
slot(slot(new("swInputData"), "output"), "timeSteps")

       [,1] [,2]
 [1,]    0    0
 [2,]    0    3
 [3,]    0    3
 [4,]    0    3
 [5,]    0    3
 [6,]    0    0
 [7,]    0    3
 [8,]    0    3
 [9,]    0    3
[10,]    0    3
[11,]    0    3
[12,]    0    3
[13,]    0    3
[14,]    0    3
[15,]    0    3
[16,]    0    3
[17,]    0    3
[18,]    0    3
[19,]    0    3
[20,]    0    3
[21,]    0    0
[22,]    0    3
[23,]    0    3
[24,]    0    3
[25,]    0    3
[26,]    0    3
[27,]    0    3
[28,]    0    0
[29,]    0    3
[30,]    0    3
```

**Comment by BrendenBe1** [comment]
Ya i clean everything and when I load the object it looks correct but when i run the examples it gives the same error.

> slot(slot(new("swInputData"), "output"), "timeSteps")
>       [,1] [,2]
>  [1,]    0    0
>  [2,]    0    3
>  [3,]    0    3
>  [4,]    0    3
>  [5,]    0    3
>  [6,]    0    0
>  [7,]    0    3
>  [8,]    0    3
>  [9,]    0    3
> [10,]    0    3
> [11,]    0    3
> [12,]    0    3
> [13,]    0    3
> [14,]    0    3
> [15,]    0    3
> [16,]    0    3
> [17,]    0    3
> [18,]    0    3
> [19,]    0    3
> [20,]    0    3
> [21,]    0    0
> [22,]    0    3
> [23,]    0    3
> [24,]    0    3
> [25,]    0    3
> [26,]    0    3
> [27,]    0    3
> [28,]    0    0
> [29,]    0    3
> [30,]    0    3
> > devtools::run_examples()

> 
> x <- new("swInputData")
> Error in validObject(.Object) : 
>   invalid class “swOUT” object: @timeSteps values must in SW_OUTNPERIODS

**Comment by dschlaep** [comment]
Without being able to reproduce this behavior, I cannot really debug

```
> devtools::run_examples()

...
Running examples in swInputData-class.Rd --------------------------------------
> 
> showClass("swInputData")
Class "swInputData" [package "rSOILWAT2"]

Slots:
                                                                  
Name:           files          years        weather          cloud
Class:        swFiles        swYears      swWeather        swCloud
                                                                  
Name:  weatherHistory         markov           prod           site
Class:           list       swMarkov         swProd         swSite
                                                                  
Name:           soils          estab         carbon         output
Class:        swSoils        swEstab       swCarbon          swOUT
                                    
Name:             swc            log
Class:          swSWC          swLog
> x <- new("swInputData")
> 
Running examples in swLog-class.Rd --------------------------------------------
...
```

**Comment by dschlaep** [comment]
What R and devtools versions are you using?
```
> getRversion()
[1] ‘3.4.3’
```
```
> packageVersion("devtools")
[1] ‘1.13.4’
```

Are you getting this error also on master commit 2ef57b2db4dff75da12f042d221db03475eba3f5?

**Comment by dschlaep** [comment]
Have tried re-producing the error with a clean fresh clone?

**Comment by dschlaep** [comment]
I am really worried that our code behaves so differently on apparent identical setups but different computers and would like to make really sure that this is so: thus, please report on your R version, devtools package version, and confirm that you have the same issue on a clean clone.

Meanwhile, I have pushed commit c7cf9755a96fbc661a967adae85e16e0570ca350 that may address your issue. If it still doesn't resolve it, then please provide also the output when you run it with the following print statements added to the `swOUT_validity` function:
```
  ok <- c(rSW2_glovars[["kSOILWAT2"]][["kINT"]][["SW_MISSING"]],
    seq_len(rSW2_glovars[["kSOILWAT2"]][["kINT"]][["SW_OUTNPERIODS"]]) - 1L) # timeSteps is base0

print(ok)
print(object@timeSteps)
print(object@timeSteps %in% ok)

  if (!all(object@timeSteps %in% ok)) {
    msg <- "@timeSteps values must be within SW_OUTNPERIODS or be equal to SW_MISSING"
    val <- if (isTRUE(val)) msg else c(val, msg)
  }
```

**Comment by BrendenBe1** [comment]
with the change you made it now runs through all of the examples without any problems

**Comment by kpalmqui** [comment]
Great. Brenden, can you also report on the following requested by Daniel:

please report on your R version, devtools package version, and confirm that you have the same issue on a clean clone

**Comment by BrendenBe1** [comment]
> > getRversion()
> [1] ‘3.4.3’
> > packageVersion("devtools")
> [1] ‘1.13.5.9000’

I did have the same issue on a clean clone but with the bugfix_114 branch changes these issues are gone.
