### ISSUE TITLE
Installation error: 'SOILWAT2/generic.h' file not found

### ISSUE THREAD

**Issue by Shanicus** [DrylandEcology/rSOILWAT2#127]
I was attempting to install `rSOILWAT2` from Github but it gave me the error:

```
SW_R_lib.c:8:10: fatal error: 'SOILWAT2/generic.h' file not found
#include "SOILWAT2/generic.h"
         ^~~~~~~~~~~~~~~~~~~~
```
Is the file actually missing or am I just missing something? Sorry, I'm not a developer or coder so I'm very unfamiliar with a lot problems that might be easy to fix!

Using macOS High Sierra v 10.13.5, R v. 3.4.3, RStudio 1.1.423

**Comment by dschlaep** [comment]
I guess that you didn't acquire the submodule source code of `SOILWAT2` as described here https://github.com/DrylandEcology/rSOILWAT2#obtain-the-source-package:
```
git clone -b master --single-branch --recursive https://github.com/DrylandEcology/rSOILWAT2.git rSOILWAT2
```
