### ISSUE TITLE
Time Period

### ISSUE THREAD

**Issue by ryanmurf** [DrylandEcology/rSOILWAT2#5]
I turned off Time Period and used the per key setting for the period. It seems that no output memory allocation happens. This might not be a bug because that setting is a stepwat setting. It might be good to make them compatible.

**Comment by ryanmurf** [comment]
@dschlaep. Could this be related to the current problem? I just noticed this hanging around.

**Comment by dschlaep** [comment]
I'm not sure to which section of the code this comment applies. Do you remember the specifics?

**Comment by dschlaep** [comment]
This is no longer an issue
