### ISSUE TITLE
Markov Weather Projects

### ISSUE THREAD

**Issue by ryanmurf** [DrylandEcology/rSOILWAT2#6]
When a project that uses Markov weather to fill in missing years of historic weather data, it has problems. This happens because the size of the list for historic weather data is allocated for every year including Markov years and then runs into problems when the list is read on execution because some are empty. Suggest fix would be to allocate memory only for number of weather files.

**Comment by dschlaep** [comment]
Ashish, you have been working on the Markov weather functionality with Trace. Could you please test whether this is still an issue or it resolved? Thanks.

**Comment by dschlaep** [comment]
closed with [v3.1.3](https://github.com/DrylandEcology/rSOILWAT2/tree/v3.1.3)
